export default {
  id: "opengateway",
  priority: 272,
  hasFree: true,
  alias: "ogw",
  aliases: [
    "ogw",
    "opengateway",
    "gitlawb",
    "gitlawb-opengateway",
  ],
  uiAlias: "ogw",
  display: {
    name: "OpenGateway",
    icon: "router",
    color: "#10B981",
    textIcon: "OGW",
    website: "https://gitlawb.com/opengateway",
    notice: {
      text: "Free Nemotron 3 Ultra (:free) & free allowance on MiMo V2.5-Pro. Pay-as-you-go inference across providers.",
      apiKeyUrl: "https://gitlawb.com/opengateway/dashboard",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  features: {
    usage: true,
    usageApikey: true,
  },
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "minimal",
      "low",
      "medium",
      "high",
      "xhigh",
      "max",
    ],
    defaultMode: "auto",
  },
  transport: {
    baseUrl: "https://opengateway.gitlawb.com/v1/chat/completions",
    validateUrl: "https://opengateway.gitlawb.com/v1/models",
  },
  transports: [
    {
      format: "openai",
      baseUrl: "https://opengateway.gitlawb.com/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
  ],
  models: [
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra (Free)", isFree: true, contextLength: 131072 },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5-Pro", contextLength: 262144 },
    { id: "xiaomi/mimo-v2.5", name: "MiMo V2.5", contextLength: 262144 },
    { id: "auto", name: "Auto (Smart Routing)" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite", contextLength: 1048576 },
    { id: "minimax/minimax-m3", name: "MiniMax M3", contextLength: 204800 },
    { id: "qwen/qwen3.7-max", name: "Qwen 3.7 Max", contextLength: 262144 },
    { id: "moonshotai/kimi-k3", name: "Kimi K3", contextLength: 1048576 },
    { id: "z-ai/glm-5.2", name: "GLM 5.2", contextLength: 1048576 },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", contextLength: 512288 },
    { id: "inclusionai/ling-3.0-flash", name: "Ling 3.0 Flash", contextLength: 262144 },
    { id: "tencent/hy3", name: "Tencent HY3", contextLength: 262144 },
    { id: "mindai/macaron-v1-tall", name: "Macaron V1 Tall", contextLength: 262144 },
    { id: "mindai/macaron-v1-venti", name: "Macaron V1 Venti", contextLength: 1048576 },
  ],
  modelsFetcher: { url: "https://opengateway.gitlawb.com/v1/models", type: "openai" },
  passthroughModels: true,
};
